"""Declarative base, naming conventions and shared column types.

Everything that every table agrees on lives here: how constraints are named,
what a money column means, and which timestamps appear on mutable records.
Centralising it is what stops twelve model files from each inventing their own
precision for a rupee.
"""

from __future__ import annotations

import datetime as dt
import re
import uuid
from decimal import Decimal
from enum import StrEnum
from typing import Annotated, Final

from sqlalchemy import BigInteger, DateTime, MetaData, Numeric, String, func, text
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Deterministic constraint names.
#:
#: Without this, PostgreSQL invents names for unnamed constraints and Alembic
#: autogenerate cannot reliably match an existing constraint to a model one —
#: which shows up as migrations that endlessly drop and recreate the same
#: index. It also makes a downgrade able to name what it is dropping.
#: Conservative pattern for values `enum_check` will interpolate into DDL.
_SAFE_ENUM_MEMBER: Final = re.compile(r"[A-Za-z0-9_]+")

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# ---------------------------------------------------------------------------
# Shared column types
# ---------------------------------------------------------------------------

#: Currency amounts.
#:
#: NUMERIC, never FLOAT: binary floating point cannot represent 0.10 exactly,
#: and a P&L that drifts by a fraction of a paisa per row is a defect that
#: compounds silently across a month of aggregation. Scale 4 rather than 2
#: because intermediate values — per-unit option premiums, brokerage, and
#: statutory charges such as STT — are quoted below the paisa. Presentation
#: quantizes to 2 at the service boundary, which already happens in
#: `domain.calculations.quantize_money`.
Money = Annotated[Decimal, mapped_column(Numeric(20, 4))]

#: Market prices. Same reasoning as `Money`; named separately because a price
#: is not an account balance and the two may diverge in precision later.
Price = Annotated[Decimal, mapped_column(Numeric(20, 4))]

#: Implied volatility, stored as a decimal fraction (0.1425 = 14.25%).
#: Six decimal places is well beyond any vendor's quoted precision.
ImpliedVolatility = Annotated[Decimal, mapped_column(Numeric(12, 6))]

#: Option Greeks. Delta spans -1..1 and gamma is frequently of order 1e-4, so
#: the scale matters more than the range.
Greek = Annotated[Decimal, mapped_column(Numeric(16, 8))]

#: Contract counts, traded volume and open interest. A liquid NIFTY weekly
#: expiry clears volumes that overflow a 32-bit integer, so BIGINT throughout.
Quantity = Annotated[int, mapped_column(BigInteger)]

#: Provenance of a row. See `app.domain.enums.DataSource` for the vocabulary.
#: Never nullable on market data: a price whose origin is unknown cannot be
#: safely used to train a model or to justify a trade.
Source = Annotated[str, mapped_column(String(32))]


def uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID primary key generated by the application.

    Generated client-side rather than by a database default so a service knows
    the identifier before it flushes, which keeps multi-table writes in one
    round trip. UUIDs rather than sequences because future ingestion may batch
    rows from several workers, and coordinating a sequence across them is a
    problem worth not having.
    """
    return mapped_column(
        postgresql.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


def created_at_column() -> Mapped[dt.datetime]:
    """Row insertion time, defaulted by the database clock."""
    return mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


def updated_at_column() -> Mapped[dt.datetime]:
    """Last modification time.

    Defaulted *and* updated server-side. An application-side `onupdate` is
    invisible to a bulk `UPDATE` statement or to a migration, which is exactly
    when an accurate timestamp matters most.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class TimestampMixin:
    """`created_at` / `updated_at` for mutable records.

    Deliberately not applied to append-only market-data tables: a candle is an
    observation of a moment, it is never edited, and an `updated_at` column on
    a billion-row hypertable is pure storage cost.
    """

    created_at: Mapped[dt.datetime] = created_at_column()
    updated_at: Mapped[dt.datetime] = updated_at_column()


def enum_check(column: str, enum: type[StrEnum]) -> str:
    """Render a CHECK expression pinning a column to a StrEnum's members.

    ENUM STRATEGY
    -------------
    The project stores closed vocabularies as `VARCHAR` plus a `CHECK`, not as
    a native PostgreSQL `ENUM`. Native enums require `ALTER TYPE` to add a
    member, which cannot run inside a transaction block in older servers and
    which Alembic cannot autogenerate. Trading vocabularies — order statuses,
    diagnostic categories, agent states — are expected to grow, and a CHECK
    constraint is rewritten by an ordinary migration.

    The Python `StrEnum` remains the single source of truth; this function
    derives the constraint from it so the two cannot drift.

    The result is interpolated into DDL, so members are validated against a
    conservative identifier pattern first. These values are developer-authored
    constants rather than request data, but a function that builds SQL by
    concatenation should refuse to do so for anything it has not inspected.
    """
    members = sorted(member.value for member in enum)
    for member in members:
        if not _SAFE_ENUM_MEMBER.fullmatch(member):
            raise ValueError(
                f"Enum member {member!r} is not safe to interpolate into DDL."
            )
    rendered = ", ".join(f"'{member}'" for member in members)
    return f"{column} IN ({rendered})"


def utcnow() -> dt.datetime:
    """Timezone-aware current time.

    `datetime.utcnow()` returns a *naive* datetime that merely happens to hold
    UTC, which compares incorrectly against every `TIMESTAMPTZ` this schema
    uses. Always aware, always explicit.
    """
    return dt.datetime.now(dt.UTC)


#: Used by migrations that must express a literal SQL default.
SQL_NOW = text("now()")
